services:
  database:
    image: postgres:17
    container_name: fp-database
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: FPPweb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: paswd123
    volumes:
      - ./docker/volumes/:/var/lib/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U fp_user']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - fp-network

networks:
  fp-network:
    driver: bridge

volumes:
  mysqldata:
